#%RAML 1.0
title:  Projet de session API
version: v1
baseUri:  http://127.0.0.1:5000/
protocols: [http]
mediaType: application/json

/bgScheduler:   
  description: update tous les jours à minuit


/api/installations:
  get:
    description: Recuperer toutes les installations selon le nom.
    responses:
      200:
        body:
          application/json:
            example:
              { "root":
                [
                  { "id" : ,
                    "nom": ,
                    "arrondissement":
                  }
                ]
              }


/api/installations/<nom_arrondissement>:
  get:
    description: Recuperer toutes les installations selon le nom d'un arrondissement
    responses:
      200:
        body:
          application/json:
            



/inscription:
  get:
    description: Un utilisateur est capable de s'inscrire à la plateforme. Ses informations sont gardées sécuritairement dans la base de données.
    responses:
      200:
        body:
          application/json:

  


